import {
  Profile,
  Client,
  Project,
  Task,
  ContentItem,
  ContentVersion,
  Approval,
  Comment,
  FileRecord,
  Notification,
  ActivityLog,
  ClientUser,
  ProjectMember,
  MonthlyCycle,
  ContentContributor,
  RecurringContentTemplate,
} from '../types/database';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'usr_admin_zeromedia',
    full_name: 'Zero Media Admin',
    email: 'zeromedia.lk@gmail.com',
    role: 'super_admin',
    status: 'active',
    job_title: 'Executive Creative Director',
    phone: '+94 77 123 4567',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'usr_pm_a',
    full_name: 'PM A',
    email: 'pm_a@zeromedia.lk',
    role: 'project_manager',
    status: 'active',
    job_title: 'Lead Retainer Project Manager',
    phone: '+94 77 234 5678',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'usr_designer_a',
    full_name: 'Designer A',
    email: 'designer_a@zeromedia.lk',
    role: 'editor',
    status: 'active',
    job_title: 'Senior Graphic & Brand Designer',
    phone: '+94 77 345 6789',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'usr_designer_b',
    full_name: 'Designer B',
    email: 'designer_b@zeromedia.lk',
    role: 'editor',
    status: 'active',
    job_title: 'Visual Content Designer',
    phone: '+94 77 456 7890',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'usr_editor_a',
    full_name: 'Video Editor A',
    email: 'editor_a@zeromedia.lk',
    role: 'editor',
    status: 'active',
    job_title: 'Lead Video & Reel Editor',
    phone: '+94 77 567 8901',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'usr_editor_b',
    full_name: 'Video Editor B',
    email: 'editor_b@zeromedia.lk',
    role: 'editor',
    status: 'active',
    job_title: 'Motion & Short-Form Specialist',
    phone: '+94 77 678 9012',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'usr_copy_c',
    full_name: 'Copy Editor C',
    email: 'copy_c@zeromedia.lk',
    role: 'copy_editor',
    status: 'active',
    job_title: 'Content Strategist & Copywriter',
    phone: '+94 77 789 0123',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'usr_client_abc',
    full_name: 'ABC Company Director',
    email: 'client@abccompany.com',
    role: 'client',
    status: 'active',
    job_title: 'Managing Director & Brand Lead',
    phone: '+1 (555) 349-8800',
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-10-01T08:00:00Z',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli_abc_company',
    company_name: 'ABC Company',
    contact_person: 'Johnathan Miller',
    email: 'client@abccompany.com',
    phone: '+1 (555) 349-8800',
    address: '742 Evergreen Terrace, Suite 400, New York, NY',
    industry: 'Retail & Consumer Lifestyle',
    notes: 'Monthly retainer partner for high-touch multi-platform social media strategy and video production.',
    status: 'active',
    assigned_pm_id: 'usr_pm_a',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-10-01T10:00:00Z',
  },
];

export const INITIAL_CLIENT_USERS: ClientUser[] = [
  {
    id: 'cu_abc_1',
    user_id: 'usr_client_abc',
    client_id: 'cli_abc_company',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    project_manager_id: 'usr_pm_a',
    project_name: 'Monthly Social Media Management',
    project_type: 'monthly_retainer',
    description: 'Ongoing monthly retainer deliverable scope for ABC Company: 5 Posts and 4 Reels every calendar month with distinct production schedules, creative briefs, client sign-offs, and publishing calendar.',
    status: 'active',
    priority: 'high',
    start_date: '2026-08-01',
    deadline: '2026-12-31',
    deliverable_targets: [
      { content_type: 'social_media_post', label: 'Posts', target_count: 5 },
      { content_type: 'reel', label: 'Reels', target_count: 4 },
    ],
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-10-01T10:00:00Z',
  },
];

export const INITIAL_PROJECT_MEMBERS: ProjectMember[] = [
  { id: 'pm_1', project_id: 'prj_abc_monthly_social', user_id: 'usr_pm_a' },
  { id: 'pm_2', project_id: 'prj_abc_monthly_social', user_id: 'usr_designer_a' },
  { id: 'pm_3', project_id: 'prj_abc_monthly_social', user_id: 'usr_designer_b' },
  { id: 'pm_4', project_id: 'prj_abc_monthly_social', user_id: 'usr_editor_a' },
  { id: 'pm_5', project_id: 'prj_abc_monthly_social', user_id: 'usr_editor_b' },
  { id: 'pm_6', project_id: 'prj_abc_monthly_social', user_id: 'usr_copy_c' },
];

export const INITIAL_MONTHLY_CYCLES: MonthlyCycle[] = [
  {
    id: 'cycle_abc_sep_2026',
    project_id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    month_name: 'September',
    month_number: 9,
    year: 2026,
    start_date: '2026-09-01',
    end_date: '2026-09-30',
    status: 'completed',
    deliverable_targets: [
      { content_type: 'social_media_post', label: 'Posts', target_count: 5 },
      { content_type: 'reel', label: 'Reels', target_count: 4 },
    ],
    notes: 'September 2026 cycle successfully delivered and published on schedule.',
    created_at: '2026-08-25T10:00:00Z',
    updated_at: '2026-09-30T18:00:00Z',
  },
  {
    id: 'cycle_abc_oct_2026',
    project_id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    month_name: 'October',
    month_number: 10,
    year: 2026,
    start_date: '2026-10-01',
    end_date: '2026-10-31',
    status: 'in_progress',
    deliverable_targets: [
      { content_type: 'social_media_post', label: 'Posts', target_count: 5 },
      { content_type: 'reel', label: 'Reels', target_count: 4 },
    ],
    notes: 'Active October 2026 retainer cycle. 5 of 9 deliverables completed. 4 remaining.',
    created_at: '2026-09-28T10:00:00Z',
    updated_at: '2026-10-02T08:00:00Z',
  },
];

export const INITIAL_CONTENT_ITEMS: ContentItem[] = [
  {
    id: 'cnt_oct_01',
    project_id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    monthly_cycle_id: 'cycle_abc_oct_2026',
    title: 'Post 01 // Autumn Showcase Carousel',
    content_type: 'social_media_post',
    platform: 'instagram',
    brief: 'High-contrast product carousel spotlighting top 4 autumn season arrivals.',
    caption: 'Autumn elegance reimagined. Discover our signature collection crafted for timeless comfort. Link in bio to shop the drop. #AutumnVibes #ABCCompany #DesignDaily',
    status: 'published',
    priority: 'high',
    assigned_to: 'usr_designer_a',
    production_start_date: '2026-10-01',
    internal_due_date: '2026-10-03',
    due_date: '2026-10-03',
    approval_date: '2026-10-04',
    publishing_date: '2026-10-05',
    actual_published_date: '2026-10-05',
    notes: 'Published on Instagram feed with carousel slider.',
    created_by: 'usr_pm_a',
    thumbnail_url: '/src/assets/images/content_beverage_ad_1790837287649.jpg',
    created_at: '2026-10-01T08:00:00Z',
    updated_at: '2026-10-05T14:30:00Z',
  },
  {
    id: 'cnt_oct_02',
    project_id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    monthly_cycle_id: 'cycle_abc_oct_2026',
    title: 'Reel 01 // Behind The Scenes Studio Teaser',
    content_type: 'reel',
    platform: 'instagram',
    brief: 'Fast-cut 15-second teaser featuring studio lighting and product craftsmanship.',
    caption: 'Crafted with obsession. A quick glimpse behind the curtain into how the autumn collection comes to life. Which detail caught your eye? #StudioBTS #Craftsmanship #ABCReels',
    status: 'published',
    priority: 'medium',
    assigned_to: 'usr_editor_a',
    contributors: [
      { id: 'cb_1', content_id: 'cnt_oct_02', user_id: 'usr_pm_a', role_in_content: 'Shooting' },
      { id: 'cb_2', content_id: 'cnt_oct_02', user_id: 'usr_copy_c', role_in_content: 'Caption' },
    ],
    production_start_date: '2026-10-03',
    internal_due_date: '2026-10-06',
    due_date: '2026-10-06',
    approval_date: '2026-10-07',
    publishing_date: '2026-10-08',
    actual_published_date: '2026-10-08',
    notes: 'Color grading matched to warm autumn palette.',
    created_by: 'usr_pm_a',
    thumbnail_url: '/src/assets/images/content_fashion_reel_1790837276139.jpg',
    created_at: '2026-10-01T08:30:00Z',
    updated_at: '2026-10-08T16:00:00Z',
  },
  {
    id: 'cnt_oct_03',
    project_id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    monthly_cycle_id: 'cycle_abc_oct_2026',
    title: 'Post 02 // Customer Review & Social Proof',
    content_type: 'social_media_post',
    platform: 'instagram',
    brief: 'Quote card graphic with verified customer testimonial and 5-star rating aesthetic.',
    caption: '"The quality exceeded every expectation." Hearing your feedback inspires everything we do. Thank you for making us part of your daily routine. #CustomerLove #Testimonial',
    status: 'published',
    priority: 'medium',
    assigned_to: 'usr_designer_b',
    production_start_date: '2026-10-06',
    internal_due_date: '2026-10-09',
    due_date: '2026-10-09',
    approval_date: '2026-10-10',
    publishing_date: '2026-10-12',
    actual_published_date: '2026-10-12',
    notes: 'Client approved copy without revisions.',
    created_by: 'usr_pm_a',
    thumbnail_url: '/src/assets/images/content_beverage_ad_1790837287649.jpg',
    created_at: '2026-10-01T09:00:00Z',
    updated_at: '2026-10-12T11:00:00Z',
  },
  {
    id: 'cnt_oct_04',
    project_id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    monthly_cycle_id: 'cycle_abc_oct_2026',
    title: 'Reel 02 // Product Feature Walkthrough',
    content_type: 'reel',
    platform: 'instagram',
    brief: 'Macro 4K video showing texture, stitching, and ergonomic utility in 20 seconds.',
    caption: 'It’s all in the details. Close-up precision that speaks for itself. Swipe up to explore specifications. #ProductShowcase #ReelOfTheDay #DesignDetails',
    status: 'published',
    priority: 'high',
    assigned_to: 'usr_editor_b',
    contributors: [
      { id: 'cb_3', content_id: 'cnt_oct_04', user_id: 'usr_designer_a', role_in_content: 'Shooting' },
      { id: 'cb_4', content_id: 'cnt_oct_04', user_id: 'usr_copy_c', role_in_content: 'Caption' },
    ],
    production_start_date: '2026-10-10',
    internal_due_date: '2026-10-13',
    due_date: '2026-10-13',
    approval_date: '2026-10-14',
    publishing_date: '2026-10-15',
    actual_published_date: '2026-10-15',
    notes: 'Macro shots graded in Rec.709.',
    created_by: 'usr_pm_a',
    thumbnail_url: '/src/assets/images/content_fashion_reel_1790837276139.jpg',
    created_at: '2026-10-01T09:30:00Z',
    updated_at: '2026-10-15T15:20:00Z',
  },
  {
    id: 'cnt_oct_05',
    project_id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    monthly_cycle_id: 'cycle_abc_oct_2026',
    title: 'Post 03 // Industry Insights Infographic',
    content_type: 'social_media_post',
    platform: 'linkedin',
    brief: 'B2B infographic on sustainability trends and modern supply chain transparency.',
    caption: 'How modern brands are transforming supply chain ethics in 2026. Key takeaways from our Q4 executive benchmark report. #IndustryInsights #B2BGrowth #Sustainability',
    status: 'published',
    priority: 'medium',
    assigned_to: 'usr_designer_a',
    production_start_date: '2026-10-12',
    internal_due_date: '2026-10-16',
    due_date: '2026-10-16',
    approval_date: '2026-10-17',
    publishing_date: '2026-10-18',
    actual_published_date: '2026-10-18',
    notes: 'Exported as PDF document & slide format for LinkedIn.',
    created_by: 'usr_pm_a',
    thumbnail_url: '/src/assets/images/content_beverage_ad_1790837287649.jpg',
    created_at: '2026-10-01T10:00:00Z',
    updated_at: '2026-10-18T10:00:00Z',
  },
  {
    id: 'cnt_oct_06',
    project_id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    monthly_cycle_id: 'cycle_abc_oct_2026',
    title: 'Reel 03 // Founder Q&A Micro-Interview',
    content_type: 'reel',
    platform: 'tiktok',
    brief: 'Informal, conversational reel with founder answering 3 community questions on brand origins.',
    caption: '"Why did we build this?" Our founder shares the raw backstory in 45 seconds. Drop your question in the comments for part two! #FounderStory #AskMeAnything #BehindTheBrand',
    status: 'client_review',
    priority: 'urgent',
    assigned_to: 'usr_editor_a',
    contributors: [
      { id: 'cb_5', content_id: 'cnt_oct_06', user_id: 'usr_pm_a', role_in_content: 'Shooting' },
      { id: 'cb_6', content_id: 'cnt_oct_06', user_id: 'usr_editor_a', role_in_content: 'Editing' },
      { id: 'cb_7', content_id: 'cnt_oct_06', user_id: 'usr_copy_c', role_in_content: 'Caption' },
    ],
    production_start_date: '2026-10-16',
    internal_due_date: '2026-10-20',
    due_date: '2026-10-20',
    client_review_date: '2026-10-20',
    publishing_date: '2026-10-22',
    notes: 'Awaiting client approval. V1 master cut uploaded for review.',
    created_by: 'usr_pm_a',
    thumbnail_url: '/src/assets/images/content_fashion_reel_1790837276139.jpg',
    created_at: '2026-10-01T10:30:00Z',
    updated_at: '2026-10-20T17:00:00Z',
  },
  {
    id: 'cnt_oct_07',
    project_id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    monthly_cycle_id: 'cycle_abc_oct_2026',
    title: 'Post 04 // Interactive Community Poll Post',
    content_type: 'social_media_post',
    platform: 'instagram',
    brief: 'Engaging 2-option carousel poll asking community to vote for their favorite colorway.',
    caption: 'Which colorway are you rocking this season: Obsidian Black or Desert Sage? Cast your vote below! 👇 #CommunityPoll #StyleChoice',
    status: 'in_production',
    priority: 'medium',
    assigned_to: 'usr_designer_b',
    production_start_date: '2026-10-19',
    internal_due_date: '2026-10-23',
    due_date: '2026-10-23',
    publishing_date: '2026-10-25',
    notes: 'Designer B is finalizing graphic mockups in Figma.',
    created_by: 'usr_pm_a',
    thumbnail_url: '/src/assets/images/content_beverage_ad_1790837287649.jpg',
    created_at: '2026-10-01T11:00:00Z',
    updated_at: '2026-10-19T09:00:00Z',
  },
  {
    id: 'cnt_oct_08',
    project_id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    monthly_cycle_id: 'cycle_abc_oct_2026',
    title: 'Reel 04 // Trending Audio Speed Run',
    content_type: 'reel',
    platform: 'instagram',
    brief: 'High energy rhythmic reel synced to trending viral audio highlighting weekly office packout.',
    caption: 'Friday speed run at the studio! When the orders stack up, we lock in. Turn audio on! 🔊 #ViralAudio #WorkHardPlayHard #ReelVibes',
    status: 'in_production',
    priority: 'medium',
    assigned_to: 'usr_editor_b',
    contributors: [
      { id: 'cb_8', content_id: 'cnt_oct_08', user_id: 'usr_editor_b', role_in_content: 'Editing' },
    ],
    production_start_date: '2026-10-22',
    internal_due_date: '2026-10-26',
    due_date: '2026-10-26',
    publishing_date: '2026-10-28',
    notes: 'Audio beat syncing in progress.',
    created_by: 'usr_pm_a',
    thumbnail_url: '/src/assets/images/content_fashion_reel_1790837276139.jpg',
    created_at: '2026-10-01T11:30:00Z',
    updated_at: '2026-10-22T10:00:00Z',
  },
  {
    id: 'cnt_oct_09',
    project_id: 'prj_abc_monthly_social',
    client_id: 'cli_abc_company',
    monthly_cycle_id: 'cycle_abc_oct_2026',
    title: 'Post 05 // Monthly Wrap & November Sneak Peek',
    content_type: 'social_media_post',
    platform: 'facebook',
    brief: 'Monthly celebration graphic reviewing community growth and teasing November holiday specials.',
    caption: 'That’s a wrap on October! Thank you for an incredible month of community milestones. November has big surprises in store... Stay tuned! #MonthlyWrap #SneakPeek #ABCCompany',
    status: 'planned',
    priority: 'low',
    assigned_to: 'usr_designer_a',
    production_start_date: '2026-10-25',
    internal_due_date: '2026-10-28',
    due_date: '2026-10-28',
    publishing_date: '2026-10-31',
    notes: 'Scheduled for end-of-month release.',
    created_by: 'usr_pm_a',
    thumbnail_url: '/src/assets/images/content_beverage_ad_1790837287649.jpg',
    created_at: '2026-10-01T12:00:00Z',
    updated_at: '2026-10-01T12:00:00Z',
  },
];

export const INITIAL_CONTENT_VERSIONS: ContentVersion[] = [
  {
    id: 'ver_oct_06_1',
    content_id: 'cnt_oct_06',
    version_number: 1,
    file_url: '/src/assets/images/content_fashion_reel_1790837276139.jpg',
    file_name: 'ABC_Founder_QA_Reel_V1_FinalCut.mp4',
    file_type: 'video/mp4',
    uploaded_by: 'usr_editor_a',
    notes: 'Master edit with dynamic captions, sound design, and color grading. Ready for client review.',
    created_at: '2026-10-20T16:45:00Z',
  },
];

export const INITIAL_CONTENT_CONTRIBUTORS: ContentContributor[] = [
  { id: 'cb_1', content_id: 'cnt_oct_02', user_id: 'usr_pm_a', role_in_content: 'Shooting' },
  { id: 'cb_2', content_id: 'cnt_oct_02', user_id: 'usr_copy_c', role_in_content: 'Caption' },
  { id: 'cb_3', content_id: 'cnt_oct_04', user_id: 'usr_designer_a', role_in_content: 'Shooting' },
  { id: 'cb_4', content_id: 'cnt_oct_04', user_id: 'usr_copy_c', role_in_content: 'Caption' },
  { id: 'cb_5', content_id: 'cnt_oct_06', user_id: 'usr_pm_a', role_in_content: 'Shooting' },
  { id: 'cb_6', content_id: 'cnt_oct_06', user_id: 'usr_editor_a', role_in_content: 'Editing' },
  { id: 'cb_7', content_id: 'cnt_oct_06', user_id: 'usr_copy_c', role_in_content: 'Caption' },
  { id: 'cb_8', content_id: 'cnt_oct_08', user_id: 'usr_editor_b', role_in_content: 'Editing' },
];

export const INITIAL_RECURRING_TEMPLATES: RecurringContentTemplate[] = [
  {
    id: 'tmpl_1',
    client_id: 'cli_abc_company',
    project_id: 'prj_abc_monthly_social',
    title: 'Weekly Product Feature Post',
    content_type: 'social_media_post',
    platform: 'instagram',
    brief: 'Weekly studio product feature with high-resolution imagery and lifestyle framing.',
    caption: 'Discover the precision behind our signature pieces. Handcrafted for modern living. #ABCCompany #WeeklyFeature',
    default_assigned_to: 'usr_designer_a',
    notes: 'Reusable standard template for weekly social feed posts.',
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'tmpl_2',
    client_id: 'cli_abc_company',
    project_id: 'prj_abc_monthly_social',
    title: 'Behind The Scenes Quick Reel',
    content_type: 'reel',
    platform: 'instagram',
    brief: 'Quick 15-30 second studio clip highlighting active workflow and team culture.',
    caption: 'How the magic happens. Step behind the lens with the Zero Media team. #BehindTheScenes #CreativeStudio',
    default_assigned_to: 'usr_editor_a',
    notes: 'Short-form BTS video format.',
    created_at: '2026-09-01T10:00:00Z',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk_1',
    project_id: 'prj_abc_monthly_social',
    assigned_to: 'usr_designer_a',
    created_by: 'usr_pm_a',
    title: 'Export autumn visual assets in 4:5 and 1:1 ratios',
    description: 'Prepare export packages for Instagram feed carousel and LinkedIn presentation format.',
    status: 'completed',
    priority: 'high',
    due_date: '2026-10-02',
    completed_at: '2026-10-02T16:00:00Z',
    created_at: '2026-10-01T08:00:00Z',
    updated_at: '2026-10-02T16:00:00Z',
  },
  {
    id: 'tsk_2',
    project_id: 'prj_abc_monthly_social',
    assigned_to: 'usr_editor_a',
    created_by: 'usr_pm_a',
    title: 'Generate subtitles & captions for Reel 03',
    description: 'Ensure burned-in and open captions for TikTok and Instagram Reel engagement.',
    status: 'in_progress',
    priority: 'urgent',
    due_date: '2026-10-21',
    created_at: '2026-10-18T09:00:00Z',
    updated_at: '2026-10-20T10:00:00Z',
  },
];

export const INITIAL_APPROVALS: Approval[] = [
  {
    id: 'appr_01',
    content_id: 'cnt_oct_01',
    client_user_id: 'usr_client_abc',
    status: 'approved',
    comment: 'Approved for publication! The color grading looks sublime.',
    created_at: '2026-10-04T12:00:00Z',
  },
  {
    id: 'appr_02',
    content_id: 'cnt_oct_02',
    client_user_id: 'usr_client_abc',
    status: 'approved',
    comment: 'Great pace and sound mix. Approved.',
    created_at: '2026-10-07T14:00:00Z',
  },
  {
    id: 'appr_03',
    content_id: 'cnt_oct_03',
    client_user_id: 'usr_client_abc',
    status: 'approved',
    comment: 'Love the testimonial card formatting.',
    created_at: '2026-10-10T11:00:00Z',
  },
  {
    id: 'appr_04',
    content_id: 'cnt_oct_04',
    client_user_id: 'usr_client_abc',
    status: 'approved',
    comment: 'Close-ups look fantastic. Ready to go live.',
    created_at: '2026-10-14T15:00:00Z',
  },
  {
    id: 'appr_05',
    content_id: 'cnt_oct_05',
    client_user_id: 'usr_client_abc',
    status: 'approved',
    comment: 'Solid B2B infographic. Approved for LinkedIn.',
    created_at: '2026-10-17T09:30:00Z',
  },
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 'comm_1',
    user_id: 'usr_editor_a',
    content_id: 'cnt_oct_06',
    comment: 'Uploaded Master V1 cut for client review. Subtitles are color-matched and audio normalized to -14 LUFS.',
    created_at: '2026-10-20T16:50:00Z',
  },
];

export const INITIAL_FILES: FileRecord[] = [
  {
    id: 'fil_1',
    client_id: 'cli_abc_company',
    project_id: 'prj_abc_monthly_social',
    content_id: 'cnt_oct_06',
    uploaded_by: 'usr_editor_a',
    file_name: 'ABC_Founder_QA_Reel_V1_FinalCut.mp4',
    file_path: '/src/assets/images/content_fashion_reel_1790837276139.jpg',
    file_type: 'video/mp4',
    file_size: '28.4 MB',
    created_at: '2026-10-20T16:45:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_1',
    user_id: 'usr_client_abc',
    title: 'Content Ready for Review',
    message: '"Reel 03 // Founder Q&A Micro-Interview" is awaiting your review and approval for October 22 publishing.',
    type: 'approval',
    related_project_id: 'prj_abc_monthly_social',
    related_content_id: 'cnt_oct_06',
    read: false,
    created_at: '2026-10-20T17:00:00Z',
  },
  {
    id: 'notif_2',
    user_id: 'usr_pm_a',
    title: 'Publishing Warning: Upcoming Deliverable',
    message: '"Reel 03 // Founder Q&A Micro-Interview" is scheduled to publish on Oct 22 and is currently in Client Review.',
    type: 'deadline',
    related_project_id: 'prj_abc_monthly_social',
    related_content_id: 'cnt_oct_06',
    read: false,
    created_at: '2026-10-20T17:05:00Z',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act_1',
    user_id: 'usr_editor_a',
    action: 'Submitted "Reel 03 // Founder Q&A Micro-Interview" for Client Review',
    entity_type: 'content',
    entity_id: 'cnt_oct_06',
    created_at: '2026-10-20T17:00:00Z',
  },
  {
    id: 'act_2',
    user_id: 'usr_client_abc',
    action: 'Approved "Post 03 // Industry Insights Infographic"',
    entity_type: 'approval',
    entity_id: 'cnt_oct_05',
    created_at: '2026-10-17T09:30:00Z',
  },
  {
    id: 'act_3',
    user_id: 'usr_pm_a',
    action: 'Launched October 2026 Monthly Retainer Cycle for ABC Company',
    entity_type: 'project',
    entity_id: 'prj_abc_monthly_social',
    created_at: '2026-10-01T08:00:00Z',
  },
];

